import React from "react";
import GelogicalMapbg from "assets/images/geologicalMapbg.png";
import GelogicalMapDarkbg from "assets/images/geologicalMapbg1.png";
import GelogicalMapLightbg from "assets/images/geologicalMapbg2.png";
import IntroContainer from "components/IntroContainer";
import { Container } from "components/UI";
import { useState, useEffects } from "react";
import BreadCrumbs from "components/Breadcrumbs";
import GeologicalData from "components/GeologicalData";
function GeologicalMap() {
  const [state, setstate] = useState("Geological Map");

  const breadcrumbs = [
    { path: "/", label: "Home" },
    { path: "/service-and-support", label: "Services and Support" },
    { path: "#", label: "Geological Data" },
  ];

  const geologicalSubHeadings = {
    "Geological Map": {
      img: GelogicalMapbg,
      content: (
        <div className="geological-map-content">
          <p>
            Geological maps provide information about the distribution, composition, & structure of rocks and minerals
            in an area, essential for identifying potential mineral deposits, understanding geological processes, &
            assessing the feasibility of resource extraction in Pakistan.
          </p>
          <br></br>
          <p>
            Geological maps provide a bird’s eye view of the surface (and subsurface) distribution of various types of
            rocks & economic minerals that are found in a particu­lar region. These maps are essential for all
            geological works including, mineral exploration, civil engineering, soil surveys, land use & soil
            conservation projects.
          </p>
          <br></br>
          <p>
            The Geological Survey of Pakistan (GSP) is primarily responsible for collection and dissemination of
            geological information about the country so that the earth’s resources could be best exploited and utilized.
            The information is compiled and disseminated in the form of reports and maps.
          </p>
        </div>
      ),
    },
    "Geochemical Map": {
      img: GelogicalMapbg,
      content: (
        <div className="geological-map-content">
          <p>
          Geochemical maps are instrumental in identifying minerals in Pakistan, offering valuable insights into the distribution of elements and minerals across the country's diverse geological terrain. These maps are generated by analyzing samples collected from rocks, soils, sediments, and surface waters, providing data on the concentration and spatial distribution of various chemical elements associated with specific mineralization types. By mapping the geochemical signatures of elements such as gold, copper, lead, zinc, and others, geologists can identify potential mineral deposits and exploration targets.
          </p>
          <br></br>
          <p>
          In Pakistan, geochemical mapping has been particularly useful in identifying anomalous concentrations of elements associated with valuable mineralization, guiding mineral exploration efforts in regions such as Balochistan, Khyber Pakhtunkhwa, and Punjab.  Additionally, geochemical maps contribute to understanding geological processes, environmental assessments, and land-use planning, making them indispensable tools for sustainable mineral resource management and economic development in Pakistan.
          </p>
        </div>
      ),
    },
    "Geophysical Map": {
      img: GelogicalMapbg,
      content: (
        <div className="geological-map-content">
          <p>
          In Pakistan, geophysical maps serve as invaluable tools for mineral mapping, offering critical insights into the country's diverse geological landscape & mineral potential. By employing various geophysical techniques, including gravity, magnetic, electrical, & seismic surveys, these maps reveal subsurface anomalies indicative of different geological features & mineral deposits. This data enables geologists to identify structural patterns, lithological variations, & prospective mineralization zones that may not be visible at the surface.
          </p>
          <br></br>
          <p>
          Through the analysis of geophysical data, Pakistan can pinpoint target areas for further exploration, aiding in the interpretation of geological processes and reducing the risk associated with drilling activities. Geophysical maps contribute to understanding the spatial distribution, size, & depth of mineral deposits, facilitating informed decision-making in resource estimation & mine planning. Geophysical mapping plays a pivotal role in unlocking Pakistan's mineral potential, guiding exploration efforts, & supporting sustainable development in the mining sector.
          </p>
        </div>
      ),
    },
    "Aerial & Imagery": {
      img: GelogicalMapbg,
      content: (
        <div className="geological-map-content">
          <p>
          Aerial maps and imagery play a vital role in mineral mapping by providing detailed and comprehensive visual data of the Earth's surface from above. These high-resolution images captured from satellites, aircraft, or drones offer valuable insights into geological features, terrain morphology, and land cover characteristics. By analyzing aerial maps and imagery, geologists and mining experts can identify geological formations, structural patterns, and potential mineral deposits that may not be visible at ground level.
          </p>
          <br></br>
          <p>
          This remote sensing technology allows for efficient and cost-effective reconnaissance of large areas, enabling mineral exploration teams to prioritize target areas for further investigation. Additionally, aerial maps and imagery facilitate the integration of geological, geochemical, and geophysical data, leading to more accurate geological interpretations and mineral resource assessments. Furthermore, aerial maps and imagery facilitate collaboration between the GSP and mining companies, providing valuable information for strategic decision-making and sustainable resource development.
          </p>
        </div>
      ),
    },
    Topography: {
      img: GelogicalMapbg,
      content: (
        <div className="geological-map-content">
          <p>
          Topographic maps play a crucial role in mineral identification in Pakistan by providing detailed information about the country's diverse terrain and geological features. These maps depict elevation contours, landforms, and geological structures, which help geologists pinpoint potential mineralization zones. In Pakistan, terrain analysis based on topographic maps can highlight specific geological formations associated with known mineral deposits, such as those found in mountainous regions like Balochistan and Khyber Pakhtunkhwa.
          </p>
          <br></br>
          <p>
          Drainage patterns visible on these maps also aid in identifying areas where minerals may have been transported and deposited by water, particularly in riverbeds and alluvial plains. Moreover, vegetation patterns on topographic maps can offer clues about underlying geology and potential mineral resources. By leveraging this detailed terrain data, mineral exploration efforts in Pakistan are guided towards promising areas for further investigation and resource development.
          </p>
        </div>
      ),
    },
  };

  const handleTab = (item) => {
    setstate(item);
  };
  return (
    <div>
      <Container classes="mt-8 w-[90%]">
        <div className="business-investment-container">
          <BreadCrumbs breadcrumbs={breadcrumbs} />
          <div className="geological-map-title">Geological Data</div>
          <div className="geological-map-subheading">
            {Object.entries(geologicalSubHeadings).map(([title, item], index) => (
              <div
                key={index}
                className="geological-map-tab"
                style={{
                  backgroundImage: `url(${title === state ? GelogicalMapDarkbg : GelogicalMapLightbg})`,
                  color: `${title === state ? "white" : "green"}`,
                  borderRadius:'20px 20px 0px 0px'
                }}
                onClick={() => handleTab(title)}
              >
                <h3>{title}</h3>
              </div>
            ))}
          </div>
          <GeologicalData
            title={state}
            content={geologicalSubHeadings[state]["content"]}
            GelogicalMapbg={geologicalSubHeadings[state]["img"]}
          ></GeologicalData>
        </div>
      </Container>
    </div>
  );
}

export default GeologicalMap;
